### ISSUE TITLE
Edge case: "awww..." is matched

### ISSUE THREAD

**Issue by eric-wood** [tenderlove/rails_autolink#46]
I'm not sure how important this is, but I figured it was worth documenting!

It turns out the regex used will match the string "awww...", which apparently occurs on a regular basis in our application :\

Example using the autolink regex: http://rubular.com/r/YsunYu1etE

**Comment by coreyhaines** [comment]
:-1: for disallowing the posting of cute cat pictures in ANY application. All applications should have AT LEAST one feature which provides pictures of cats.

**Comment by ramhoj** [comment]
Fixed in #75 and released in v1.1.7. Credits to @ItsYou for the original solution in #57. Closing.
