### ISSUE TITLE
parse URLs that end in dashes

### ISSUE THREAD

**Issue by tylercal** [tenderlove/rails_autolink#52]
``` ruby
auto_link('http://example.com/e-')
```

should return

``` html
<a href="http://example.com/e-">http://example.com/e-</a>
```

but returns

``` html
<a href="http://example.com/e">http://example.com/e</a>-
```

**Comment by coreyhaines** [comment]
Can you give a concrete example of a live URL that has this happen? Seems weird to have a url ending with a hyphen. Is that even a valid url?

**Comment by tylercal** [comment]
The case that I ran into involved a URL to redeem a gift code. Hyphen is a valid character for URLs, so I assume their system generates a random URL from the valid character set which can sometimes end in a hyphen. 

I agree that it's unusual, but I don't think it's in anyway invalid.

**Comment by tylercal** [comment]
I did some searching around, looks like Drupal can generate URLs that end in hyphens too: https://productforums.google.com/forum/m/#!topic/webmasters/tBv3MKghw0Y

**Comment by sinsoku** [comment]
[Devise.friendly_token](https://github.com/plataformatec/devise/blob/v4.2.0/lib/devise.rb#L477) generate URL that end in dash too.
This issue occurs when we give URL including `Devise.friendly_token` to `auto_link`. As below:

```rb
auto_link('https://example.com/confirm?token=MRPEkBAJyHgBUFNgpLs-')
#=> "<a href=\"https://example.com/confirm?token=MRPEkBAJyHgBUFNgpLs\">https://example.com/confirm?token=MRPEkBAJyHgBUFNgpLs</a>-"
```
