### ISSUE TITLE
Feature request: make `auto_link` takes a block

### ISSUE THREAD

**Issue by PikachuEXE** [tenderlove/rails_autolink#54]
Now:

``` haml
- auto_link_content = capture do
  -# content
= auto_link(auto_link_content, options)
```

Expected

``` haml
= auto_link(options) do
  -# content
```

**Comment by coreyhaines** [comment]
Hmmm.... Could you give a concrete example of when you've needed this? All the times I've used the gem, it was for auto-linking either user-supplied content or other text that was already in a string. If you are in a template, why not just write with the html?

**Comment by PikachuEXE** [comment]
My content is from locale files, which is like:
```yaml
For enquiries or feedback, email us at
contact@test.com
For press enquiries, email us at
press@test.com
To speak to one of us, call 1234567.
```
SInce the email location might change (since sentence structure changes for different locales)
we either need to separate the paragraph structure and the email addresses into different locale keys, which is inconvenient, or just put it into a single paragraph, and use `simple_format` + `auto_link`.
