### ISSUE TITLE
auto_link method not found just after a require

### ISSUE THREAD

**Issue by AlexCppns** [tenderlove/rails_autolink#59]
`undefined method `auto_link' for #<CampaignSerializer:..`

**Comment by asoap** [comment]
I just ran into this also.  It turns out I was using this in the model.  This is apparently only a view helper, so it wouldn't work.  Perhaps you're doing something similar?

**Comment by coreyhaines** [comment]
Yeah, this is mixed into the view helpers. https://github.com/tenderlove/rails_autolink/blob/master/lib/rails_autolink/helpers.rb#L9-L11

**Comment by asoap** [comment]
Yeah.  I just used the Sanitize gem in the model to remove any extra html tags I didn't want, then used this in the view.

**Comment by kssmilik** [comment]
In serializers you can use ``ActionController::Base.helpers.auto_link(text)``
