### ISSUE TITLE
Short text to hide URL

### ISSUE THREAD

**Issue by clreddy21** [tenderlove/rails_autolink#62]
I there a way to hide show only text to the user rather than whole url in the view, like following,

[google](www.google.co.in) instead of [www.google.co.in](www.google.co.in), if not could you please make one.

**Comment by coreyhaines** [comment]
No, there isn't right now. The code doesn't have any logic like that; it just goes through and wraps anything that looks like a url in an `a` tag

**Comment by clreddy21** [comment]
hey, thank you for the reply, but I found a way out, by directly storing the url's in html format(anchor tags) in db.
